name: navigation
description: A project demonstrating clean architecture
publish_to: "none"
version: 1.0.0+1

environment:
  flutter: ">=3.38.4"
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  auto_route: ^11.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_markdown: ^0.7.7+1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  google_fonts: ^7.0.2
  http_parser: ^4.1.2
  json_annotation: ^4.9.0
  palette_generator: ^0.3.3+7
  pretty_dio_logger: ^1.4.0
  retrofit: 4.9.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4

dev_dependencies:
  auto_route_generator: ^10.4.0
  bloc_test: ^10.0.0
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  retrofit_generator: 10.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

flutter_gen:
  output: lib/generated/
